import Providers from "@/components/ui/Provider";
import "./globals.css";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "CHAT | APP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
